version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - ./mount:/var/lib/postgresql/data
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
        environment: 
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            - DEBUG=${DEBUG}
            - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
            - DATABASE_ENGINE=${DATABASE_ENGINE}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_PORT=${DATABASE_PORT}
            - DJANGO_LOGLEVEL=${DJANGO_LOGLEVEL}
        volumes:
            - .:/usr/src/app
        ports:
            - "${DJANGO_PORT}:${DJANGO_PORT}"
        depends_on: 
            - db
