# Generated by Django 3.1.1 on 2020-10-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201019_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_root',
            new_name='root_post',
        ),
    ]
