#!/bin/bash

cd /home/ec2-user/TinyTwitter

docker build -t tinytwitter .
docker run --detach \
           --name tinytwitter_web \
           --expose 8000:8000 \
           --volume /var/www/tinytwitter.zhaosean.com/public:/var/www/tinytwitter.zhaosean.com/public \
           --env-file .env \
           tinytwitter

docker exec -it tinytwitter_web python manage.py collectstatic